# Generated by Django 3.2.13 on 2022-05-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('alert', models.BooleanField()),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarms.states')),
            ],
        ),
    ]
