# Generated by Django 3.2.13 on 2022-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
